"""Update only title/OG/Twitter metadata, with auditable visible-copy evidence.

Dry run: python -X utf8 tools/personalize_title_suffixes.py
Apply:   python -X utf8 tools/personalize_title_suffixes.py --write
Verify:  python -X utf8 tools/personalize_title_suffixes.py --check
Run after any page generator; no manuscript is regenerated by this tool.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
import hashlib
import html
import json
import math
from pathlib import Path
import re
from urllib.parse import unquote, urlparse, urljoin

from title_suffix_rules import RULES, CATEGORY_SUFFIXES

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / 'tools/reports/title-suffix-audit.json'
TITLE_RE = re.compile(r'(<title\b[^>]*>)(.*?)(</title>)', re.I | re.S)
META_RE = re.compile(r'<meta\b[^>]*>', re.I | re.S)
ATTR_RE = re.compile(r'''([:\w-]+)\s*=\s*(["'])(.*?)\2''', re.S)
SECTION_RE = re.compile(r'<section\b([^>]*)>(.*?)</section>', re.I | re.S)
BLOCK_RE = re.compile(r'<(h2|h3|p)\b[^>]*>(.*?)</\1>', re.I | re.S)
COMPILED = [(label, subject, re.compile(pattern)) for label, subject, pattern in RULES]


def clean(value):
    return ' '.join(html.unescape(re.sub(r'<[^>]+>', ' ', value)).split())


def attrs(tag):
    return {key.lower(): html.unescape(value) for key, _, value in ATTR_RE.findall(tag)}


def title_of(source):
    match = TITLE_RE.search(source)
    if not match:
        raise ValueError('missing title')
    return html.unescape(match[2]).strip()


def replace_titles(source, title):
    escaped = html.escape(title, quote=True)
    source, count = TITLE_RE.subn(lambda m: m[1] + escaped + m[3], source)
    if count != 1:
        raise ValueError(f'title count {count}')

    def meta(match):
        tag = match[0]
        data = attrs(tag)
        if data.get('property') != 'og:title' and data.get('name') != 'twitter:title':
            return tag
        tag, n = re.subn(r'''(\bcontent\s*=\s*)(["'])(.*?)\2''',
                        lambda m: m[1] + m[2] + escaped + m[2], tag, flags=re.S)
        if n != 1:
            raise ValueError('title meta content is missing')
        return tag

    return META_RE.sub(meta, source)


def masked(source):
    """Byte-level guard: ALL content except the three allowed values is fixed."""
    return replace_titles(source, '__TITLE_ONLY__')


def sha(value):
    return hashlib.sha256(value.encode('utf-8')).hexdigest()


def read_page(path):
    source = path.read_bytes().decode('utf-8')
    title = title_of(source)
    base = re.split(r'[|｜]', title, maxsplit=1)[0].strip()
    rel = path.relative_to(ROOT).as_posix()
    parts = rel.split('/')[:-1]
    main_match = re.search(r'<main\b[^>]*>(.*?)</main>', source, re.I | re.S)
    if not main_match:
        raise ValueError(f'missing main: {rel}')
    main = main_match[1]
    main = re.sub(r'<(script|style|nav)\b[^>]*>.*?</\1>', '', main, flags=re.I | re.S)
    visible = clean(main)
    metas = [attrs(m[0]) for m in META_RE.finditer(source)]
    canonical = re.search(r'<link\b[^>]*rel=["\']canonical["\'][^>]*href=["\']([^"\']+)', source, re.I)
    if not canonical:
        raise ValueError(f'missing canonical: {rel}')
    if parts[0] == '전국학원':
        kind = {2:'region',3:'district',4:'locality',5:'national-course'}[len(parts)]
        group = ('전국학원/' + parts[-1]) if kind == 'national-course' else kind
    else:
        kind = 'category' if len(parts) == 2 else ('center' if parts[1] == '와와학습코칭센터' else 'subject')
        group = parts[1] if kind == 'subject' else kind

    # Only authored learning sections, not links/FAQ/fee tables/registration.
    sections = []
    for match in SECTION_RE.finditer(main):
        if ('subject-copy-section' in match[1] or 'seo-answer-section' in match[1]
                or 'subject-quick-answer' in match[1]):
            if any(x in match[1] for x in ['school', 'review', 'faq']):
                continue
            text = clean(match[2])
            if '실제 수업 가능 학교와' in text[:160] or '학교 원자료 상태와' in text[:160]:
                continue
            sections.append((match[1], match[2]))
    blocks = []
    for index, (attributes, fragment) in enumerate(sections):
        for tag, text in BLOCK_RE.findall(fragment):
            value = clean(text)
            if len(value) < 12:
                continue
            # Focus the distinctive intent/persona, not the footer boilerplate.
            weight = 1.0
            if 'seo-answer-section' in attributes:
                weight = 5.0
            elif 'subject-quick-answer' in attributes:
                weight = 3.5
            elif index < 3:
                weight = 4.0
            if tag in ('h2','h3'):
                weight += 1.0
            blocks.append((value, weight))
    # Older national manuscripts use article/div rather than section wrappers.
    # Include their paragraphs at low weight; retain the intent section priority.
    prose = main
    for match in list(SECTION_RE.finditer(main))[::-1]:
        if any(word in match[1] for word in ('faq','review','related','network','school-reference','school-manuscript')):
            prose=prose[:match.start()]+prose[match.end():]
    known={value for value,_ in blocks}
    for tag,text in BLOCK_RE.findall(prose):
        value=clean(text)
        if tag=='p' and len(value)>30 and value not in known:
            blocks.append((value,.5))
            known.add(value)
    return dict(path=path, source=source, title=title, base=base, rel=rel, parts=parts,
                kind=kind, group=group, main=main, visible=visible, blocks=blocks,
                metas=metas, canonical=html.unescape(canonical[1]))


def content_candidates(page):
    category = page['parts'][1] if page['parts'][0] == '과목별학원' else page['parts'][-1]
    only_math = category in ('고등수학학원','중등수학학원')
    only_english = category in ('고등영어학원','중등영어학원')
    found = []
    for label, subject, pattern in COMPILED:
        if (only_math and subject == 'english') or (only_english and subject == 'math'):
            continue
        if any(grade in category for grade in ('초등','중등','중학생')) and label=='내신·모의고사 구분':
            continue
        evidence = []
        score = 0
        for block, weight in page['blocks']:
            match = pattern.search(block)
            if match:
                evidence.append((block, match[0], weight))
                score += weight
        if evidence:
            best = max(evidence, key=lambda x:x[2])
            # Repetition is weak evidence; a distinctive prominent passage wins.
            found.append(dict(label=label,subject=subject,score=best[2]*4 + min(score,12),
                              excerpt=best[0],match=best[1]))
    return found


def linked_localities(page):
    explicit=re.search(r'<div\b[^>]*class="center-profile-localities"[^>]*>(.*?)</div>',page['main'],re.S)
    if explicit:
        names=[clean(x) for x in re.findall(r'<span\b[^>]*>(.*?)</span>',explicit[1],re.S)]
        if names:
            return list(dict.fromkeys(names))
    result=[]
    for target in re.findall(r'<a\b[^>]*href=["\']([^"\']+)', page['main'], re.I):
        decoded = unquote(urljoin(page['canonical'],html.unescape(target)))
        pieces = urlparse(decoded).path.strip('/').split('/')
        if len(pieces) == 4 and pieces[0] == '전국학원' and pieces[-1] not in result:
            result.append(pieces[-1])
    return result


def directory_suffix(page):
    parts=page['parts']; kind=page['kind']; visible=page['visible']
    if kind == 'category':
        label, terms=CATEGORY_SUFFIXES[parts[1]]
        for term in terms:
            if term not in visible:
                raise ValueError(f'{page["rel"]}: missing category evidence {term}')
        return label,[dict(label=label,match=' / '.join(terms),excerpt=visible[:650])]
    if kind == 'region':
        districts=len(list(page['path'].parent.glob('*/index.html')))
        localities=len(list(page['path'].parent.glob('*/*/index.html')))
        label=f'{districts}개 시군구·{localities}개 동네 안내'
        # Counts come from real linked descendants, never a claimed branch count.
        return label,[dict(label=label,match=f'{districts} / {localities}',excerpt='실제 하위 index.html 목록 집계')]
    if kind == 'district':
        names=sorted(p.name for p in page['path'].parent.iterdir() if p.is_dir() and (p/'index.html').exists())
        if not names:
            raise ValueError(f'{page["rel"]}: no locality')
        location='·'.join(names[:2])
        if len(names)>2:
            location+=' 등'
        label=f'{location} 위치·학년 안내'
        for name in names[:2]:
            if name not in visible:
                raise ValueError(f'{page["rel"]}: locality absent from copy {name}')
        return label,[dict(label=label,match=' / '.join(names[:2]),excerpt=visible[:650])]
    if kind == 'center':
        names=linked_localities(page)
        if not names:
            raise ValueError(f'{page["rel"]}: center locality not found')
        label='·'.join(names[:2]) + ' 위치·가능 학년'
        return label,[dict(label=label,match=' / '.join(names[:2]),excerpt=visible[:650])]
    raise ValueError(kind)


def plan(pages):
    grouped=defaultdict(list)
    for page in pages:
        if page['kind'] in ('subject','locality','national-course'):
            page['candidates']=content_candidates(page)
            if len(page['candidates'])<2:
                raise ValueError(f'{page["rel"]}: fewer than two supported learning topics')
            grouped[page['group']].append(page)
        else:
            page['suffix'],page['evidence']=directory_suffix(page)

    for group, members in grouped.items():
        frequencies=Counter(c['label'] for p in members for c in p['candidates'])
        used=Counter()
        for page in members:
            candidates=page['candidates']
            for c in candidates:
                subject_boost=1.35 if (group in ('고등수학학원','중등수학학원','고등영어학원','중등영어학원') and c['subject']) else 1
                c['rank']=c['score']*subject_boost*(1 + .15*math.log((len(members)+1)/(frequencies[c['label']]+1)))
            candidates.sort(key=lambda c:(-c['rank'],c['label']))
            # Alternatives are limited to evidence close to the strongest topic.
            firsts=[c for c in candidates[:8] if c['rank']>=candidates[0]['rank']*.90]
            pairs=[]
            for first in firsts:
                for second in candidates[:16]:
                    if first is second or first['label'] in second['label'] or second['label'] in first['label']:
                        continue
                    redundant_groups=(
                        {'주간 학습 흐름','수업·숙제·복습 연결','주간 계획의 실행'},
                        {'서술형 풀이 근거','서술형 답안 구성'},
                        {'스스로 설명하는 공부','배운 내용 회상'},
                        {'독해 근거 찾기','선택지 판단 근거'},
                    )
                    if any({first['label'],second['label']}<=family for family in redundant_groups):
                        continue
                    if len(set(first['label'].split()) & set(second['label'].split()))>1:
                        continue
                    suffix=first['label']+'·'+second['label']
                    if len(suffix)>34 or len(page['base']+' | '+suffix)>75:
                        continue
                    pair_key=tuple(sorted((first['label'],second['label'])))
                    score=first['rank']+second['rank']*.66 - min(used[pair_key],6)*.8
                    pairs.append((score,suffix,first,second))
            if not pairs:
                raise ValueError(f'{page["rel"]}: no concise supported pair')
            _,suffix,first,second=max(pairs,key=lambda x:(x[0],x[1]))
            page['suffix']=suffix
            page['evidence']=[{k:c[k] for k in ('label','match','excerpt')} for c in (first,second)]
            used[tuple(sorted((first['label'],second['label'])))]+=1

    for p in pages:
        p['new_title']=p['base']+' | '+p['suffix']
        p['updated']=replace_titles(p['source'],p['new_title'])
        if masked(p['source'])!=masked(p['updated']):
            raise ValueError(f'{p["rel"]}: non-title content changed')
        if len(p['suffix'])>40 or len(p['new_title'])>85:
            raise ValueError(f'{p["rel"]}: overly long title')
        if p['new_title'].count('|')!=1:
            raise ValueError(f'{p["rel"]}: separator count')
        for meta in [attrs(m[0]) for m in META_RE.finditer(p['updated'])]:
            if meta.get('property')=='og:title' or meta.get('name')=='twitter:title':
                if meta.get('content')!=p['new_title']:
                    raise ValueError(f'{p["rel"]}: social title mismatch')
    if len({p['new_title'] for p in pages})!=len(pages):
        raise ValueError('duplicate complete titles')


def rss_update(pages):
    path=ROOT/'rss.xml'
    source=path.read_bytes().decode('utf-8')
    by_url={unquote(p['canonical']):p for p in pages}
    count=0
    def item(m):
        nonlocal count
        block=m[0]
        link=re.search(r'<link>(.*?)</link>',block,re.S)
        if not link:return block
        page=by_url.get(unquote(html.unescape(link[1])))
        if not page:return block
        new=re.sub(r'(<title>).*?(</title>)',lambda x:x[1]+html.escape(page['new_title'])+x[2],block,count=1,flags=re.S)
        count+=new!=block
        return new
    updated=re.sub(r'<item>.*?</item>',item,source,flags=re.S)
    return source,updated,count


def run():
    parser=argparse.ArgumentParser()
    mode=parser.add_mutually_exclusive_group()
    mode.add_argument('--write',action='store_true')
    mode.add_argument('--check',action='store_true')
    args=parser.parse_args()
    paths=sorted(p for top in ('전국학원','과목별학원') for p in (ROOT/top).rglob('index.html') if p.parent!=ROOT/top)
    with ThreadPoolExecutor(max_workers=8) as pool:
        pages=list(pool.map(read_page,paths))
    plan(pages)
    rss_old,rss_new,rss_changes=rss_update(pages)
    stats={}
    for group in sorted({p['group'] for p in pages}):
        members=[p for p in pages if p['group']==group]
        counts=Counter(p['suffix'] for p in members)
        stats[group]=dict(pages=len(members),uniqueSuffixes=len(counts),mostRepeated=counts.most_common(4))
    changed=[p for p in pages if p['source']!=p['updated']]
    old_entries={}
    if REPORT.exists():
        old_entries={row['path']:row for row in json.loads(REPORT.read_text(encoding='utf-8'))['entries']}
    def before_title(p):
        old=old_entries.get(p['rel'])
        if old and old['unchangedContentSha256']==sha(masked(p['source'])):
            return old['before']
        return p['title']
    report=dict(pages=len(pages),changed=len(changed),rssTitlesChanged=rss_changes,
                uniqueTitles=len({p['new_title'] for p in pages}),
                uniqueSuffixes=len({p['suffix'] for p in pages}),
                titleLength=dict(min=min(len(p['new_title']) for p in pages),max=max(len(p['new_title']) for p in pages)),
                nonTitleChanges=0,groups=stats,entries=[dict(path=p['rel'],url=p['canonical'],
                  before=before_title(p),after=p['new_title'],suffix=p['suffix'],
                  unchangedContentSha256=sha(masked(p['source'])),evidence=p['evidence']) for p in pages])
    if args.write:
        REPORT.parent.mkdir(parents=True,exist_ok=True)
        for p in changed:
            p['path'].write_bytes(p['updated'].encode('utf-8'))
        if rss_old!=rss_new:
            (ROOT/'rss.xml').write_bytes(rss_new.encode('utf-8'))
        REPORT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    elif not args.check:
        REPORT.parent.mkdir(parents=True,exist_ok=True)
        REPORT.with_name('title-suffix-plan.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    print(json.dumps({k:v for k,v in report.items() if k!='entries'},ensure_ascii=False,indent=2))
    for p in [p for p in pages if '명일' in p['rel']][:14]:
        print(p['new_title'])
    if args.check and (changed or rss_changes):
        raise SystemExit('FAIL: generated titles are not up to date')
    print('TITLE_SUFFIX_'+('CHECK' if args.check else 'WRITE' if args.write else 'PLAN')+'_PASS')


if __name__=='__main__':
    run()
